package uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-12-20T14:39:18.636-03:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://bps.gub.uy/recaudacion/facturacion/v001", name = "WsEmisorDocumentoService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsEmisorDocumentoService {

    @WebMethod(action = "obtenerDocumentosPorEmpresa")
    @RequestWrapper(localName = "obtenerDocumentosPorEmpresa", targetNamespace = "http://bps.gub.uy/recaudacion/facturacion/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ObtenerDocumentosPorEmpresa")
    @ResponseWrapper(localName = "obtenerDocumentosPorEmpresaResponse", targetNamespace = "http://bps.gub.uy/recaudacion/facturacion/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ObtenerDocumentosPorEmpresaResponse")
    @WebResult(name = "resultObtenerDocumentosPorEmpresa", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ResultObtenerDocumentosPorEmpresa obtenerDocumentosPorEmpresa(

        @WebParam(name = "paramObtenerDocumentosPorEmpresa", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ParamObtenerDocumentosPorEmpresa paramObtenerDocumentosPorEmpresa
    );

    @WebMethod(action = "version")
    @RequestWrapper(localName = "version", targetNamespace = "http://bps.gub.uy/recaudacion/facturacion/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.Version")
    @ResponseWrapper(localName = "versionResponse", targetNamespace = "http://bps.gub.uy/recaudacion/facturacion/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.VersionResponse")
    @WebResult(name = "resultVersion", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ResultVersion version()
;

    @WebMethod(action = "obtenerObtenerDocumentoAutogestionado")
    @RequestWrapper(localName = "obtenerDocumentoAutogestionado", targetNamespace = "http://bps.gub.uy/recaudacion/facturacion/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ObtenerDocumentoAutogestionado")
    @ResponseWrapper(localName = "obtenerDocumentoAutogestionadoResponse", targetNamespace = "http://bps.gub.uy/recaudacion/facturacion/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ObtenerDocumentoAutogestionadoResponse")
    @WebResult(name = "resultObtenerDocumentoAutogestionado", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ResultObtenerDocumentoAutogestionado obtenerDocumentoAutogestionado(

        @WebParam(name = "paramObtenerDocumentoAutogestionado", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ParamObtenerDocumentoAutogestionado paramObtenerDocumentoAutogestionado
    );

    @WebMethod(action = "obtenerDocumentoPagoACuenta")
    @RequestWrapper(localName = "obtenerDocumentoPagoACuenta", targetNamespace = "http://bps.gub.uy/recaudacion/facturacion/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ObtenerDocumentoPagoACuenta")
    @ResponseWrapper(localName = "obtenerDocumentoPagoACuentaResponse", targetNamespace = "http://bps.gub.uy/recaudacion/facturacion/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ObtenerDocumentoPagoACuentaResponse")
    @WebResult(name = "resultObtenerDocumentoPagoACuenta", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ResultObtenerDocumentoPagoACuenta obtenerDocumentoPagoACuenta(

        @WebParam(name = "paramObtenerDocumentoPagoACuenta", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ParamObtenerDocumentoPagoACuenta paramObtenerDocumentoPagoACuenta
    );

    @WebMethod(action = "obtenerDocumentoPDF")
    @RequestWrapper(localName = "obtenerDocumentoPDF", targetNamespace = "http://bps.gub.uy/recaudacion/facturacion/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ObtenerDocumentoPDF")
    @ResponseWrapper(localName = "obtenerDocumentoPDFResponse", targetNamespace = "http://bps.gub.uy/recaudacion/facturacion/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ObtenerDocumentoPDFResponse")
    @WebResult(name = "resultObtenerDocumentoPDF", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ResultObtenerDocumentoPDF obtenerDocumentoPDF(

        @WebParam(name = "paramObtenerDocumentoPDF", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ParamObtenerDocumentoPDF paramObtenerDocumentoPDF
    );

    @WebMethod(action = "obtenerFactura")
    @RequestWrapper(localName = "obtenerFactura", targetNamespace = "http://bps.gub.uy/recaudacion/facturacion/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ObtenerFactura")
    @ResponseWrapper(localName = "obtenerFacturaResponse", targetNamespace = "http://bps.gub.uy/recaudacion/facturacion/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ObtenerFacturaResponse")
    @WebResult(name = "resultObtenerFactura", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ResultObtenerFactura obtenerFactura(

        @WebParam(name = "paramObtenerFactura", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService.ParamObtenerFactura paramObtenerFactura
    );
}
