package uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorDocumentoService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-12-20T14:39:18.702-03:00
 * Generated source version: 4.0.4
 *
 */
@WebServiceClient(name = "WsEmisorDocumentoService",
                  wsdlLocation = "http://srvh2122:8080/Facturacion/WsEmisorDocumentoService/V001/WsEmisorDocumentoService?wsdl",
                  targetNamespace = "http://bps.gub.uy/recaudacion/facturacion/v001")
public class WsEmisorDocumentoService_Service extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://bps.gub.uy/recaudacion/facturacion/v001", "WsEmisorDocumentoService");
    public static final QName WsEmisorDocumento = new QName("http://bps.gub.uy/recaudacion/facturacion/v001", "WsEmisorDocumento");
    static {
        URL url = null;
        try {
            url = new URL("http://srvh2122:8080/Facturacion/WsEmisorDocumentoService/V001/WsEmisorDocumentoService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsEmisorDocumentoService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://srvh2122:8080/Facturacion/WsEmisorDocumentoService/V001/WsEmisorDocumentoService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsEmisorDocumentoService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsEmisorDocumentoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsEmisorDocumentoService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WsEmisorDocumentoService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WsEmisorDocumentoService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WsEmisorDocumentoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WsEmisorDocumentoService
     */
    @WebEndpoint(name = "WsEmisorDocumento")
    public WsEmisorDocumentoService getWsEmisorDocumento() {
        return super.getPort(WsEmisorDocumento, WsEmisorDocumentoService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsEmisorDocumentoService
     */
    @WebEndpoint(name = "WsEmisorDocumento")
    public WsEmisorDocumentoService getWsEmisorDocumento(WebServiceFeature... features) {
        return super.getPort(WsEmisorDocumento, WsEmisorDocumentoService.class, features);
    }

}
