package uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-12-20T14:38:19.854-03:00
 * Generated source version: 4.0.4
 *
 */
@WebServiceClient(name = "WsRegEmpresasService",
                  wsdlLocation = "http://proxyservt.bps.net/Registros/Empresas/V003/WsRegEmpresasService?wsdl",
                  targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003")
public class WsRegEmpresasService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://bps.gub.uy/atyr/registro/empresas/v003", "WsRegEmpresasService");
    public static final QName WsRegEmpresasV003 = new QName("http://bps.gub.uy/atyr/registro/empresas/v003", "WsRegEmpresasV003");
    static {
        URL url = null;
        try {
            url = new URL("http://proxyservt.bps.net/Registros/Empresas/V003/WsRegEmpresasService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsRegEmpresasService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://proxyservt.bps.net/Registros/Empresas/V003/WsRegEmpresasService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsRegEmpresasService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsRegEmpresasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsRegEmpresasService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WsRegEmpresasService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WsRegEmpresasService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WsRegEmpresasService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WsRegEmpresaV003
     */
    @WebEndpoint(name = "WsRegEmpresasV003")
    public WsRegEmpresaV003 getWsRegEmpresasV003() {
        return super.getPort(WsRegEmpresasV003, WsRegEmpresaV003.class);
    }

}
