package uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-12-20T14:38:19.779-03:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", name = "WsRegEmpresaV003")
@XmlSeeAlso({ObjectFactory.class})
public interface WsRegEmpresaV003 {

    @WebMethod(action = "obtenerListaEmpresa")
    @RequestWrapper(localName = "obtenerListaEmpresa", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerListaEmpresa")
    @ResponseWrapper(localName = "obtenerListaEmpresaResponse", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerListaEmpresaResponse")
    @WebResult(name = "resultObtenerListaEmpresa", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ResultObtenerListaEmpresa obtenerListaEmpresa(

        @WebParam(name = "paramObtenerListaEmpresaEmpresa", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ParamObtenerListaEmpresa paramObtenerListaEmpresaEmpresa
    );

    @WebMethod(action = "obtenerEstadosAportacion")
    @RequestWrapper(localName = "obtenerEstadosAportacion", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerEstadosAportacion")
    @ResponseWrapper(localName = "obtenerEstadosAportacionResponse", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerEstadosAportacionResponse")
    @WebResult(name = "resultObtenerEstadosAportacion", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ResultObtenerEstadosAportacion obtenerEstadosAportacion(

        @WebParam(name = "paramObtenerEstadosAportacion", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ParamObtenerEstadosAportacion paramObtenerEstadosAportacion
    );

    @WebMethod(action = "obtenerListaRelContribuyente")
    @RequestWrapper(localName = "obtenerListaRelContribuyente", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerListaRelContribuyente")
    @ResponseWrapper(localName = "obtenerListaRelContribuyenteResponse", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerListaRelContribuyenteResponse")
    @WebResult(name = "resultObtenerListaRelContribuyente", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ResultObtenerListaRelContribuyente obtenerListaRelContribuyente(

        @WebParam(name = "paramObtenerListaRelContribuyente", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ParamObtenerListaRelContribuyente paramObtenerListaRelContribuyente
    );

    @WebMethod(action = "obtenerEmpresa")
    @RequestWrapper(localName = "obtenerEmpresa", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerEmpresa")
    @ResponseWrapper(localName = "obtenerEmpresaResponse", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerEmpresaResponse")
    @WebResult(name = "resultObtenerEmpresa", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ResultObtenerEmpresa obtenerEmpresa(

        @WebParam(name = "paramObtenerEmpresa", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ParamObtenerEmpresa paramObtenerEmpresa
    );

    @WebMethod(action = "obtenerAtributosEspecialesEmpresa")
    @RequestWrapper(localName = "obtenerAtributosEspecialesEmpresa", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerAtributosEspecialesEmpresa")
    @ResponseWrapper(localName = "obtenerAtributosEspecialesEmpresaResponse", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerAtributosEspecialesEmpresaResponse")
    @WebResult(name = "resultObtenerAtributosEspecialesEmpresa", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ResultObtenerAtributosEspecialesEmpresa obtenerAtributosEspecialesEmpresa(

        @WebParam(name = "paramObtenerAtributoEspecialEmpresa", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ParamObtenerAtributoEspecialEmpresa paramObtenerAtributoEspecialEmpresa
    );

    @WebMethod(action = "obtenerListaEstadosAportacion")
    @RequestWrapper(localName = "obtenerListaEstadosAportacion", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerListaEstadosAportacion")
    @ResponseWrapper(localName = "obtenerListaEstadosAportacionResponse", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerListaEstadosAportacionResponse")
    @WebResult(name = "resultObtenerListaEstadosAportacion", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ResultObtenerListaEstadosAportacion obtenerListaEstadosAportacion(

        @WebParam(name = "paramObtenerListaEstadosAportacion", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ParamObtenerListaEstadosAportacion paramObtenerListaEstadosAportacion
    );

    @WebMethod(action = "obtenerListaRelContribuyenteEmpresas")
    @RequestWrapper(localName = "obtenerListaRelContribuyenteEmpresas", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerListaRelContribuyenteEmpresas")
    @ResponseWrapper(localName = "obtenerListaRelContribuyenteEmpresasResponse", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerListaRelContribuyenteEmpresasResponse")
    @WebResult(name = "resultObtenerListaRelContribuyenteEmpresas", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ResultObtenerListaRelContribuyenteEmpresas obtenerListaRelContribuyenteEmpresas(

        @WebParam(name = "paramObtenerListaRelContribuyenteEmpresas", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ParamObtenerListaRelContribuyenteEmpresas paramObtenerListaRelContribuyenteEmpresas
    );

    @WebMethod(action = "obtenerLocales")
    @RequestWrapper(localName = "obtenerLocales", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerLocales")
    @ResponseWrapper(localName = "obtenerLocalesResponse", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerLocalesResponse")
    @WebResult(name = "resultobtenerLocales", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ResultObtenerLocales obtenerLocales(

        @WebParam(name = "paramObtenerLocales", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ParamObtenerLocales paramObtenerLocales
    );

    @WebMethod(action = "obtenerDomicilioFiscalPpal")
    @RequestWrapper(localName = "obtenerDomicilioFiscalPpal", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerDomicilioFiscalPpal")
    @ResponseWrapper(localName = "obtenerDomicilioFiscalPpalResponse", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerDomicilioFiscalPpalResponse")
    @WebResult(name = "resultObtenerDomicilioFiscalPpal", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ResultObtenerDomicilioFiscalPpal obtenerDomicilioFiscalPpal(

        @WebParam(name = "paramObtenerDomicilioFiscalPpal", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ParamObtenerDomicilioFiscalPpal paramObtenerDomicilioFiscalPpal
    );

    @WebMethod(action = "obtenerContribuyenteVigente")
    @RequestWrapper(localName = "obtenerContribuyenteVigente", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerContribuyenteVigente")
    @ResponseWrapper(localName = "obtenerContribuyenteVigenteResponse", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ObtenerContribuyenteVigenteResponse")
    @WebResult(name = "resultObtenerContribuyenteVigente", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ResultObtenerContribuyenteVigente obtenerContribuyenteVigente(

        @WebParam(name = "paramObtenerContribuyenteVigente", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ParamObtenerContribuyenteVigente paramObtenerContribuyenteVigente
    );

    @WebMethod(action = "validarEmpresa")
    @RequestWrapper(localName = "validarEmpresa", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ValidarEmpresa")
    @ResponseWrapper(localName = "validarEmpresaResponse", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ValidarEmpresaResponse")
    @WebResult(name = "resultValidarEmpresa", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ResultValidarEmpresa validarEmpresa(

        @WebParam(name = "paramValidarEmpresa", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ParamValidarEmpresa paramValidarEmpresa
    );

    @WebMethod(action = "version")
    @RequestWrapper(localName = "version", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.Version")
    @ResponseWrapper(localName = "versionResponse", targetNamespace = "http://bps.gub.uy/atyr/registro/empresas/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.VersionResponse")
    @WebResult(name = "version", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegEmpresasService.ResultVersion version()
;
}
