# Docker
DOCKERFILE_PATH="ci/docker/spring-boot/Dockerfile"
DOCKER_BUILD_PATH="."

DOCKER_REGISTRY_UPLOAD="nexus.bps.net:5001"
DOCKER_REGISTRY_DOWNLOAD="nexus.bps.net:5000"
DOCKER_USER=$NEXUS_USER
DOCKER_PASSWORD=$NEXUS_PASSWORD

# Application
APP_IMAGE_PATH="$OPENSHIFT_PROJECT/$APP_NAME"
export APP_BUILDER_IMAGE_TAG_LATEST="$APP_IMAGE_PATH-builder:latest"

