package uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-12-20T13:27:31.760-03:00
 * Generated source version: 4.0.4
 *
 */
@WebServiceClient(name = "WsRegContribuyenteService",
                  wsdlLocation = "http://proxyservt.bps.net/Registros/Empresas/V003/WsRegContribuyenteService?wsdl",
                  targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003")
public class WsRegContribuyenteService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://bps.gub.uy/registro/contribuyentes/v003", "WsRegContribuyenteService");
    public static final QName WsRegContribuyenteV003 = new QName("http://bps.gub.uy/registro/contribuyentes/v003", "WsRegContribuyenteV003");
    static {
        URL url = null;
        try {
            url = new URL("http://proxyservt.bps.net/Registros/Empresas/V003/WsRegContribuyenteService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsRegContribuyenteService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://proxyservt.bps.net/Registros/Empresas/V003/WsRegContribuyenteService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsRegContribuyenteService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsRegContribuyenteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsRegContribuyenteService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WsRegContribuyenteService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WsRegContribuyenteService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WsRegContribuyenteService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WsRegContribuyenteV003
     */
    @WebEndpoint(name = "WsRegContribuyenteV003")
    public WsRegContribuyenteV003 getWsRegContribuyenteV003() {
        return super.getPort(WsRegContribuyenteV003, WsRegContribuyenteV003.class);
    }

}
