package uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-12-20T13:27:31.702-03:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", name = "WsRegContribuyenteV003")
@XmlSeeAlso({ObjectFactory.class})
public interface WsRegContribuyenteV003 {

    @WebMethod(action = "obtenerNaturalezasJuridicas")
    @RequestWrapper(localName = "obtenerNaturalezasJuridicas", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ObtenerNaturalezasJuridicas")
    @ResponseWrapper(localName = "obtenerNaturalezasJuridicasResponse", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ObtenerNaturalezasJuridicasResponse")
    @WebResult(name = "resultObtenerNaturalezasJuridicas", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ResultObtenerNaturalezasJuridicas obtenerNaturalezasJuridicas(

        @WebParam(name = "paramObtenerNaturalezasJuridicas", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ParamObtenerNaturalezasJuridicas paramObtenerNaturalezasJuridicas
    );

    @WebMethod(action = "obtenerIntegrantesFisicos")
    @RequestWrapper(localName = "obtenerIntegrantesFisicos", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ObtenerIntegrantesFisicos")
    @ResponseWrapper(localName = "obtenerIntegrantesFisicosResponse", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ObtenerIntegrantesFisicosResponse")
    @WebResult(name = "ResultObtenerIntegrantesFisicos", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ResultObtenerIntegrantesFisicos obtenerIntegrantesFisicos(

        @WebParam(name = "paramObtenerIntegrantesFisicos", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ParamObtenerIntegrantesFisicos paramObtenerIntegrantesFisicos
    );

    @WebMethod(action = "obtenerAtributosEspeciales")
    @RequestWrapper(localName = "obtenerAtributosEspeciales", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ObtenerAtributosEspeciales")
    @ResponseWrapper(localName = "obtenerAtributosEspecialesResponse", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ObtenerAtributosEspecialesResponse")
    @WebResult(name = "resultObtenerAtributosEspeciales", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ResultObtenerAtributosEspeciales obtenerAtributosEspeciales(

        @WebParam(name = "paramObtenerAtributosEspeciales", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ParamObtenerAtributosEspeciales paramObtenerAtributosEspeciales
    );

    @WebMethod(action = "obtenerListaRelEmpresa")
    @RequestWrapper(localName = "obtenerListaRelEmpresa", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ObtenerListaRelEmpresa")
    @ResponseWrapper(localName = "obtenerListaRelEmpresaResponse", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ObtenerListaRelEmpresaResponse")
    @WebResult(name = "resultObtenerListaRelEmpresa", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ResultObtenerListaRelEmpresa obtenerListaRelEmpresa(

        @WebParam(name = "paramObtenerListaRelEmpresa", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ParamObtenerListaRelEmpresa paramObtenerListaRelEmpresa
    );

    @WebMethod(action = "version")
    @RequestWrapper(localName = "version", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.Version")
    @ResponseWrapper(localName = "versionResponse", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.VersionResponse")
    @WebResult(name = "version", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ResultVersion version()
;

    @WebMethod(action = "obtenerIntegrantesJuridicos")
    @RequestWrapper(localName = "obtenerIntegrantesJuridicos", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ObtenerIntegrantesJuridicos")
    @ResponseWrapper(localName = "obtenerIntegrantesJuridicosResponse", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ObtenerIntegrantesJuridicosResponse")
    @WebResult(name = "resultObtenerIntegrantesJuridicos", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ResultObtenerIntegrantesJuridicos obtenerIntegrantesJuridicos(

        @WebParam(name = "paramObtenerIntegrantesJuridicos", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ParamObtenerIntegrantesJuridicos paramObtenerIntegrantesJuridicos
    );

    @WebMethod(action = "obtenerListaContribuyente")
    @RequestWrapper(localName = "obtenerListaContribuyente", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ObtenerListaContribuyente")
    @ResponseWrapper(localName = "obtenerListaContribuyenteResponse", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ObtenerListaContribuyenteResponse")
    @WebResult(name = "resultObtenerListaContribuyente", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ResultObtenerListaContribuyente obtenerListaContribuyente(

        @WebParam(name = "paramObtenerListaContribuyente", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ParamObtenerListaContribuyente paramObtenerListaContribuyente
    );

    @WebMethod(action = "validarContribuyente")
    @RequestWrapper(localName = "validarContribuyente", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ValidarContribuyente")
    @ResponseWrapper(localName = "validarContribuyenteResponse", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ValidarContribuyenteResponse")
    @WebResult(name = "resultValidarContribuyente", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ResultValidarContribuyente validarContribuyente(

        @WebParam(name = "paramValidarContribuyente", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ParamValContribuyente paramValidarContribuyente
    );

    @WebMethod(action = "obtenerContribuyentesPorPersona")
    @RequestWrapper(localName = "obtenerContribuyentesPorPersona", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ObtenerContribuyentesPorPersona")
    @ResponseWrapper(localName = "obtenerContribuyentesPorPersonaResponse", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ObtenerContribuyentesPorPersonaResponse")
    @WebResult(name = "resultObtenerContribuyentesPorPersona", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ResultObtenerContribuyentesPorPersona obtenerContribuyentesPorPersona(

        @WebParam(name = "paramObtenerContribuyentesPorPersona", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ParamObtenerContribuyentesPorPersona paramObtenerContribuyentesPorPersona
    );

    @WebMethod(action = "obtenerContribuyente")
    @RequestWrapper(localName = "obtenerContribuyente", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ObtenerContribuyente")
    @ResponseWrapper(localName = "obtenerContribuyenteResponse", targetNamespace = "http://bps.gub.uy/registro/contribuyentes/v003", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ObtenerContribuyenteResponse")
    @WebResult(name = "resultObtenerContribuyente", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ResultObtenerContribuyente obtenerContribuyente(

        @WebParam(name = "paramObtenerContribuyente", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsRegContribuyenteService.ParamObtenerContribuyente paramObtenerContribuyente
    );
}
