package uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-12-20T14:39:57.128-03:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://bps.gub.uy/recaudacion/wsEmisorConsultas/v001", name = "WsEmisorConsulta")
@XmlSeeAlso({ObjectFactory.class})
public interface WsEmisorConsulta {

    @WebMethod(action = "obtenerUltimoDocumento")
    @RequestWrapper(localName = "obtenerUltimoDocumento", targetNamespace = "http://bps.gub.uy/recaudacion/wsEmisorConsultas/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ObtenerUltimoDocumento")
    @ResponseWrapper(localName = "obtenerUltimoDocumentoResponse", targetNamespace = "http://bps.gub.uy/recaudacion/wsEmisorConsultas/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ObtenerUltimoDocumentoResponse")
    @WebResult(name = "ResultObtenerUltimoDocumento", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ResultObtenerUltimoDocumento obtenerUltimoDocumento(

        @WebParam(name = "ParamObtenerUltimoDocumento", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ParamObtenerUltimoDocumento paramObtenerUltimoDocumento
    );

    @WebMethod(action = "obtenerDuplicadoDocumento")
    @RequestWrapper(localName = "obtenerDuplicadoDocumento", targetNamespace = "http://bps.gub.uy/recaudacion/wsEmisorConsultas/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ObtenerDuplicadoDocumento")
    @ResponseWrapper(localName = "obtenerDuplicadoDocumentoResponse", targetNamespace = "http://bps.gub.uy/recaudacion/wsEmisorConsultas/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ObtenerDuplicadoDocumentoResponse")
    @WebResult(name = "ResultObtenerDuplicadoDocumentoWs", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ResultObtenerDuplicadoDocumentoWs obtenerDuplicadoDocumento(

        @WebParam(name = "ParamObtenerDuplicadoDocumento", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ParamObtenerDuplicadoDocumento paramObtenerDuplicadoDocumento
    );

    @WebMethod(action = "version")
    @RequestWrapper(localName = "version", targetNamespace = "http://bps.gub.uy/recaudacion/wsEmisorConsultas/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.Version")
    @ResponseWrapper(localName = "versionResponse", targetNamespace = "http://bps.gub.uy/recaudacion/wsEmisorConsultas/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.VersionResponse")
    @WebResult(name = "resultVersion", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ResultVersion version()
;

    @WebMethod(action = "obtenerDocumentosPorNroReferencia")
    @RequestWrapper(localName = "obtenerDocumentosPorNroReferencia", targetNamespace = "http://bps.gub.uy/recaudacion/wsEmisorConsultas/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ObtenerDocumentosPorNroReferencia")
    @ResponseWrapper(localName = "obtenerDocumentosPorNroReferenciaResponse", targetNamespace = "http://bps.gub.uy/recaudacion/wsEmisorConsultas/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ObtenerDocumentosPorNroReferenciaResponse")
    @WebResult(name = "ResultObtenerDocumentosPorNroReferenciaWs", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ResultObtenerDocumentosPorNroReferenciaWs obtenerDocumentosPorNroReferencia(

        @WebParam(name = "ParamObtenerDocumentoPorNroReferencia", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ParamObtenerDocumentosPorNroReferencia paramObtenerDocumentoPorNroReferencia
    );

    @WebMethod(action = "obtenerDocumentosPorNroResumen")
    @RequestWrapper(localName = "obtenerDocumentosPorNroResumen", targetNamespace = "http://bps.gub.uy/recaudacion/wsEmisorConsultas/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ObtenerDocumentosPorNroResumen")
    @ResponseWrapper(localName = "obtenerDocumentosPorNroResumenResponse", targetNamespace = "http://bps.gub.uy/recaudacion/wsEmisorConsultas/v001", className = "uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ObtenerDocumentosPorNroResumenResponse")
    @WebResult(name = "ResultObtenerDocumentosPorNroResumenWs", targetNamespace = "")
    public uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ResultObtenerDocumentosPorNroResumen obtenerDocumentosPorNroResumen(

        @WebParam(name = "ParamObtenerDocumentosPorNroResumen", targetNamespace = "")
        uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta.ParamObtenerDocumentosPorNroResumen paramObtenerDocumentosPorNroResumen
    );
}
