package uy.gub.bps.csda.facturas_persona.web_services.soap.wsEmisorConsulta;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-12-20T14:39:57.190-03:00
 * Generated source version: 4.0.4
 *
 */
@WebServiceClient(name = "WsEmisorConsulta",
                  wsdlLocation = "http://srvh2122:8080/Recaudacion/Emisor/V001/WsEmisorConsulta?wsdl",
                  targetNamespace = "http://bps.gub.uy/recaudacion/wsEmisorConsultas/v001")
public class WsEmisorConsulta_Service extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://bps.gub.uy/recaudacion/wsEmisorConsultas/v001", "WsEmisorConsulta");
    public static final QName WsEmisorConsulta = new QName("http://bps.gub.uy/recaudacion/wsEmisorConsultas/v001", "WsEmisorConsulta");
    static {
        URL url = null;
        try {
            url = new URL("http://srvh2122:8080/Recaudacion/Emisor/V001/WsEmisorConsulta?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsEmisorConsulta_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://srvh2122:8080/Recaudacion/Emisor/V001/WsEmisorConsulta?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsEmisorConsulta_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsEmisorConsulta_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsEmisorConsulta_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WsEmisorConsulta_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WsEmisorConsulta_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WsEmisorConsulta_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WsEmisorConsulta
     */
    @WebEndpoint(name = "WsEmisorConsulta")
    public WsEmisorConsulta getWsEmisorConsulta() {
        return super.getPort(WsEmisorConsulta, WsEmisorConsulta.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsEmisorConsulta
     */
    @WebEndpoint(name = "WsEmisorConsulta")
    public WsEmisorConsulta getWsEmisorConsulta(WebServiceFeature... features) {
        return super.getPort(WsEmisorConsulta, WsEmisorConsulta.class, features);
    }

}
